---
title: "p8105_hw5_mc5698"
output: github_document
date: "2024-11-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(rvest)
library(broom)
```
#Problem 1
```{r}
# Run the simulation
birthday_sim = 
  function(n) {
  birthdays <- sample(1:365, n, replace = TRUE)
  return(any(duplicated(birthdays))) 
}
```

```{r}
set.seed(123)
sim_results_df =
  expand_grid(
  group_size = 2:50,
  iter = 1:10000
) |>
  mutate(
    has_shared_birthday = map_lgl(group_size, birthday_sim)
  )
```

```{r}
# plot
birthday_prob <- sim_results_df %>%
  group_by(group_size) %>%
  summarize(probability = mean(has_shared_birthday))

ggplot(birthday_prob, aes(x = group_size, y = probability)) +
  geom_line() +
  labs(title = "Probability that at least two people share a birthday",
       x = "Group Size",
       y = "Probability of Shared Birthday") +
  theme_minimal()

```

#Problem 2
```{r}
# Simulation parameters
n <- 30
sigma <- 5
mu_values <- 0:6
n_simulations <- 5000
alpha <- 0.05
```

```{r}
#Define function
one_sample_sim = function(mu) {
  x <- rnorm(n, mean = mu, sd = sigma)
  t_test_result <- t.test(x, mu = 0) %>% 
    tidy() %>% 
    select(estimate, p.value)  
  colnames(t_test_result) <- c("mu_hat", "p_value")
  return(t_test_result)
}
```

```{r}
#Run the simulation
set.seed(123) 
sim_results_df <- expand_grid(
  mu = 0:6,
  iter = 1:5000
) %>%
  mutate(
    test_results = map(mu, one_sample_sim)
  ) %>%
  unnest(test_results)

```

```{r}
power_analysis = sim_results_df %>%
  group_by(mu) %>%
  summarize(
    power = mean(p_value < alpha),
    avg_mu_hat = mean(mu_hat),             
    avg_mu_hat_rejected = mean(mu_hat[p_value < alpha], na.rm = TRUE))
```

```{r}
# Plot power as a function of mu
ggplot(power_analysis, aes(x = mu, y = power)) +
  geom_line() +
  labs(title = "Power of One Sample t-Test by Effect Size",
       x = "True Mean (mu)",
       y = "Power") +
  theme_minimal()

```

```{r}
# Plot the average estimate of ðœ‡Ì‚ on the y axis and the true value of ðœ‡ on the x axis.
ggplot(power_analysis, aes(x = mu)) +
  geom_line(aes(y = avg_mu_hat, color = "All Samples")) +
  geom_line(aes(y = avg_mu_hat_rejected, color = "Rejected Samples")) +
  labs(title = "Average Estimate of mu_hat by Effect Size",
       x = "True Mean (mu)",
       y = "Average Estimate of mu_hat") +
  scale_color_manual(name = "Legend", values = c("All Samples" = "green", "Rejected Samples" = "blue")) +
  theme_minimal()
```

#Problem 3
